const text = {
  allusers: "All users",
  brandName: "me-chitrakar",
  userByPlan: "User By Plan",
  userByProfession: "User By Profession",
  booking: "Booking",
  todaysUser: "Today's User",
  revenue: "Revenue",
  dashboard: "Dashboard",
  post: "Post",
  category: "Category",
  slider: "Slider",
  mainCategory: "MAIN CATEGORY",
  subCategory: "SUB CATEGORY",
  searchKeyword: "Search Keyword",
  addPost: "Add Post",
  categories: "Categories",
  addCategory: "Add Category",
  send: "Send",
  name: "Name",
  slider: "Slider",
  link: "link",
  title: "title",
  addSlider: "Add Slider",
};
export default text;
