const text = {
  allusers: "All users",
  brandName: "me-chitrakar",
  userByPlan: "User By Plan",
  userByProfession: "User By Profession",
  booking: "Booking",
  todaysUser: "Today's User",
  revenue: "Revenue",
  dashboard: "Dashboard",
  post: "Post",
  category: "Category",
  slider: "Slider",
  mainCategory: "MAIN CATEGORY",
  subCategory: "SUB CATEGORY",
  searchKeyword: "Search Keyword",
  addPost: "Add Post",
  categories: "Categories",
  addCategory: "Add Category",
  send: "Send",
  name: "Name",
  slider: "Slider",
  link: "link",
  title: "title",
  addSlider: "Add Slider",
  addSubAdmin: "Add Sub-Admin",
  subAdmins: "Sub Admins",
  subAdminName: "Sub-Admin Name",
  subAdminEmail: "Sub Admin Email",
  subAdminPassword: "Sub Admin Password",
  subAdminRetypePass: "Sub Admin Retype Password",
  save: "Save",
  viewBusiness: "View Business",
};
export default text;
